### ISSUE TITLE
Undertow Memory Leak

### ISSUE THREAD

**Issue by catandgrep** [wildfly/wildfly#8263] opened 2015-10-09 11:32 UTC
Wildfly doesn't seem not to release "io.undertow.servlet.spec.ServletContextImpl" properly after Application Undeployments. This results in Memory Leak after contiuous redeployments of a single application:

```
6 instances of "io.undertow.servlet.spec.ServletContextImpl", loaded by "org.jboss.modules.ModuleClassLoader @ 0xe0226c10" occupy 5,051,528 (14.46%) bytes.

Biggest instances:

io.undertow.servlet.spec.ServletContextImpl @ 0xe1b64db8 - 1,039,080 (2.97%) bytes.
io.undertow.servlet.spec.ServletContextImpl @ 0xe1e7bfe8 - 1,038,960 (2.97%) bytes.
io.undertow.servlet.spec.ServletContextImpl @ 0xe16e23f8 - 1,038,536 (2.97%) bytes.
io.undertow.servlet.spec.ServletContextImpl @ 0xe1a745d0 - 1,038,488 (2.97%) bytes.
io.undertow.servlet.spec.ServletContextImpl @ 0xe1696090 - 893,456 (2.56%) bytes.
```

I've created a simple Test for reproducing this issue:
https://github.com/catandgrep/wildfly-undertow-mem-leak

**Comment by ctomc** [comment] 2015-10-09 14:09
Tnx for reproducer, I think I know where the issue lies.

**Comment by catandgrep** [comment] 2015-10-09 14:52
Nice. Looking forward to understand the root cause.

**Comment by ctomc** [comment] 2015-10-09 16:43
root cause is/was missing call to Servlet.destroy() in undertow code on undeploy. 
see https://github.com/undertow-io/undertow/issues/337 for the fix.
Memory leak "originates" from arquillian servlet protocol impl as it holds reference to ServletContext in ThreadLocal and clears it in destroy() method which was not called by container.

As workaround if you see this in testing, until this is fully merged in undertow & wildfly, you can use jmx protocol instead.

**Comment by stuartwdouglas** [comment] 2015-10-13 13:11
I have revered the Undertow change. This is actually an Arquillian bug, destroy() is called however it is called by a different thread to the service() method.

**Closed by stuartwdouglas** 2015-10-13 13:11 UTC

**Comment by ctomc** [comment] 2015-10-14 09:10
Created issue for arquillian https://issues.jboss.org/browse/ARQ-1992
